version: '2'
services:
  lightsactuator:
    build: ./Actuator
    command: ["./wait-for-it.sh", "kafka", "python", "actuatorMain.py", "-vm"] #, "-debug"]
    networks:
      - webnet
  simtemp:
    build: ./Simulator
    command: ["python", "simMain.py", "temperature", "-vm"]
    networks:
      - webnet
  simhum:
    build: ./Simulator
    command: ["python", "simMain.py", "humidity", "-vm"]
    networks:
      - webnet
  simuco2:
    build: ./Simulator
    command: ["python", "simMain.py", "co2", "-vm"]
    networks:
      - webnet
  simmov:
    build: ./Simulator
    command: ["python", "simMain.py", "movement", "-vm"]
    networks:
      - webnet
  simen:
    build: ./Simulator
    command: ["python", "simMain.py", "energy", "-vm"]
    networks:
      - webnet
  consumer:
    build: ./Consumer
    ports:
      - "5555:5555"
    command: ["./wait-for-it.sh", "kafka", "python", "consumerMain.py", "-vm"]
    networks:
      - webnet
  dashboard:
    build: ./Dashboard
    ports:
      - 8888:8080
    networks:
      - webnet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8010:8080
    networks:
      - webnet
networks:
  webnet: